# remap C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind-key a  send-prefix

# split panes using | and -
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# reload configuration file
bind r source-file ~/.tmux.conf \; display "Reloaded"

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# don't rename windows automatically
set-option -g allow-rename off

# Start windows and panes at 1, not 0
setw -g base-index 1
setw -g pane-base-index 1

# Move the window positions with ctrl+shift+arrow
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Allow swap pane commands to be repeatable
bind-key -r \{ swap-pane -U
bind-key -r \} swap-pane -D


# Allow swap layout to be repeatable
bind-key -r Space next-layout

# Escape time
set escape-time 0

# Re-order window tabs
bind R move-window -r \; display-message "Windows reordered..."

# Bind the tmux and os copy buffers
# bind -t vi-copy y copy-pipe "xclip -sel clip -i"

# bind-key -t vi-copy 'v' begin-selection
# bind-key -t vi-copy 'y' copy-selection

set-option -g default-shell $SHELL

set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"
set-option -g status-position top

# Sessionizer popup
bind-key -n C-f display-popup -E -w 80% -h 80% "tmux-sessionizer"
bind-key -n C-g display-popup -E -w 80% -h 80% "gwts"
bind-key -n C-x display-popup -E -w 80% -h 80% "tmux-session-kill"

run '~/.tmux/plugins/tpm/tpm'
